### ISSUE TITLE
Rebinding exit build mode

### ISSUE THREAD

**Issue by Zaflis** [xMGZx/better-controls#1]
Would it be possible to add a custom keybind to exiting build mode? In vanilla game it is hard-coded to right mouse button. ESC should also work always.

Because we can't rebind it, it is not feasible to change camera rotating to right mouse, since rotating camera in build mode would exit it...

**Comment by mathgeniuszach** [comment]
After re-looking over the code I don't think I'm going to implement this, as adding extra keybinds to the list would require modification of a whole lot more modifications and patches of IL (and probably certain unity assets as well) that I don't really want to do...
